---
title: noureddinedotbiz
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
  archive:
    title: Archive
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: work
  values:
    layout: work
- scope:
    path: ''
    type: archive
  values:
    layout: work
email: emailme@noureddine.biz
description: Personal portfolio 2020
baseurl:
url:
twitter_username: noureddinemade
github_username: noureddinemade
